services:
  dev:
    image: node:22
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "tail -f /dev/null"

  build-prod:
    image: node:22
    profiles: [prod]
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm run prod"
